### ISSUE TITLE
Different function names and arguments

### ISSUE THREAD

**Issue by st3r30byt3** [tevora-threat/SharpView#1]
Hi! First, well done on porting PowerView to C#. This is a great move and will surely be incredibly useful for Red Teamers and others.

I was wondering whether it was a design decision to change function names (eg: Invoke-ShareFinder is now Find_DomainShare) and to change argument names and in some cases remove arguments all together.

In my opinion, it would be great to stay coherent to make everyone's life easier :) Also, in the case of removing arguments, this is a shame because for example at the moment you cannot find shares in a more stealthy manner (-NoPing -ExcludeStandard). This being opensource, I'd be happy to contribute if this was not intentional and the idea was to include all the functionality from PowerView.

There was clearly a massive amount of work put into this so well done and thanks.

**Comment by e0x70i** [comment]
It maps to powerview dev branch: https://powersploit.readthedocs.io/en/latest/Recon/Find-DomainShare/ 

We welcome pull requests if you would like to bring some of those args back!
